# -*- coding: utf-8 -*-
"""Statistics_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V_uzoX430iKB70u21AispSz2ITFC4JTv

Practice on Descriptive Statistics
"""

# Calculate the mean

def mean_function(mydata):
  return sum(mydata)/len(mydata)

print(mean_function([1,2,3,4,5,6,7,8,9]))

# Calculate the mean using Python statistics module

import statistics

print(statistics.mean([1,2,3,4,5,6,7,8,9]))

# Calculate the median

def median_function(mydata):
  num = len(mydata)
  median_index = num // 2

  if num % 2 == 0:
    return sorted(mydata)[median_index]
  return sum(sorted(mydata)[median_index -1: median_index + 1]) / 2

print(median_function([1,2,3,4,5,6,7,8,9]))
print(median_function([1,2,3,4,5,6,7,8]))

# Calculate the median using Python statistics module

import statistics

print(statistics.median([1,2,3,4,5,6,7,8,9]))
print(statistics.median([1,2,3,4,5,6,7,8]))

from collections import Counter

def mode_function(mydata):
  c = Counter(mydata)
  return [k for k, v in c.items() if v == c.most_common(1)[0][1]]


print(mode_function([1,2,3,4,5,6,6,7,8,9]))
print(mode_function(["oranges", "apples", "pears", "oranges"]))

print(mode_function([1,2,3,4,5,6,6,7,7,8,8,9]))
print(mode_function(["oranges", "apples", "pears", "oranges", "apples"]))

import statistics

print(statistics.mode([1,2,3,4,5,6,7,7,8,9]))
print(statistics.mode(["oranges", "apples", "pears","oranges"]))